# Generated by Django 4.2.1 on 2023-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='productpictures',
            index=models.Index(fields=['product'], name='products_pr_product_1932ec_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['name', 'deleted'], name='products_pr_name_90ff80_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['sub_category', 'deleted'], name='products_pr_sub_cat_4b8cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['seller', 'deleted'], name='products_pr_seller__3e625e_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category'], name='products_su_categor_c902bf_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['name'], name='products_su_name_4ac726_idx'),
        ),
    ]
