# Generated by Django 4.2.1 on 2023-05-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='identifier',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='identifier',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=12, unique=True),
        ),
    ]
