# Generated by Django 4.2.1 on 2023-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_deleted_alter_products_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
