# Generated by Django 4.2.1 on 2023-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_deleted_products_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('stock', 'Stock'), ('sold', 'Sold'), ('bidding', 'Bidding')], default='init', max_length=10),
        ),
    ]
