# Generated by Django 4.2.1 on 2023-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hashId',
            field=models.CharField(default=1234, max_length=12),
            preserve_default=False,
        ),
    ]
