# Generated by Django 4.2.1 on 2023-05-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_hashid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveIndex(
            model_name='products',
            name='products_pr_sub_cat_4b8cd7_idx',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='products_ca_name_693421_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category', 'deleted'], name='products_pr_categor_34c085_idx'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
